server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  # Loki läuft im Docker Compose Netzwerk unter dem Dienstnamen 'loki' auf Port 3100
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    # Dies weist Promtail an, die Docker-Logs zu sammeln
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        # Der 'web' Container wird über seine Container-ID gematcht

    # Fügt jedem Log-Eintrag Labels hinzu
    relabel_configs:
      # Fügt 'container_name' als Label hinzu
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container_name"
      # Fügt den 'job' Label hinzu, basierend auf dem Containernamen
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "job"
      # Entfernt das 'slash'-Zeichen vom Anfang des Containernamens
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "instance"
      # Fügt den Log-Stream (stdout/stderr) als Label hinzu
      - source_labels: ["__meta_docker_log_stream"]
        target_label: "stream"
